workspace(name = "custom")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_jvm_external",
    sha256 = "d85951a92c0908c80bd8551002d66cb23c3434409c814179c0ff026b53544dab",
    strip_prefix = "rules_jvm_external-3.3",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/3.3.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
        maven.artifact(
            "org.clojure",
            "clojure",
            "1.10.1",
            exclusions = [
                "org.clojure:core.specs.alpha",
                "org.clojure:spec.alpha",
            ],
        ),
        maven.artifact(
            "org.clojure",
            "spec.alpha",
            "0.2.176",
            exclusions = [
                "org.clojure:clojure",
            ],
        ),
        maven.artifact(
            "org.clojure",
            "core.specs.alpha",
            "0.2.44",
            exclusions = [
                "org.clojure:clojure",
            ],
        ),
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
        "https://repo.clojars.org",
    ],
)

local_repository(
    name = "rules_clojure",
    path = "../../..",
)

register_toolchains("//:custom_toolchain")
