workspace(name = "default")

local_repository(
    name = "rules_clojure",
    path = "../../..",
)

load("@rules_clojure//:repositories.bzl", "rules_clojure_deps")
rules_clojure_deps()

load("@rules_clojure//:setup.bzl", "rules_clojure_setup")
rules_clojure_setup()
