workspace(name = "default")

local_repository(
    name = "rules_clojure",
    path = "../../..",
)

load("@rules_clojure//:repositories.bzl", "rules_clojure_dependencies", "rules_clojure_toolchains")

rules_clojure_dependencies()

rules_clojure_toolchains()
